- hosts: 10.30.8.47    #replace with target host 
  remote_user: ubuntu
  roles:
  - role: 5g_catalogue_prerequisites
  - kafka
  
- hosts: 10.30.8.47    #replace with target host 
  remote_user: ubuntu
  tasks:

  - name: remove 5gcatalogue folder
    file: 
      path: 5gcatalogue
      state: absent

  - name: remove nfv-sol-libs folder
    file: 
      path: nfv-sol-libs
      state: absent

  - name: remove nfv-ifa-libs folder
    file: 
      path: nfv-ifa-libs
      state: absent

  - git:
      repo: 'https://github.com/nextworks-it/5g-catalogue.git'
      dest: 5gcatalogue

  - git:
      repo: 'https://github.com/nextworks-it/nfv-sol-libs.git'
      dest: nfv-sol-libs
      version: v3.1

  - git:
      repo: 'https://github.com/nextworks-it/nfv-ifa-libs.git'
      dest: nfv-ifa-libs
      version: v1.0

  - name: creating 5gcatalogue log directory
    become: true
    remote_user: ubuntu
    file:
      path: /var/log/5gcatalogue
      state: directory
      mode: '0666'

  - name: creating postgres user
    become: true
    postgresql_user:
      name: postgres
      password: postgres
    become_user: postgres

  - postgresql_db:
      name: cataloguedb
      owner: postgres
    become_user: postgres
    become: true

  - name: BUILDING NFV-SOL-LIB DEPENDENCIES...COMMON
    remote_user: ubuntu
    shell: /opt/apache-maven-3.3.9/bin/mvn clean install  
    args:
      chdir: nfv-sol-libs/NFV_MANO_SOL001_LIBS_COMMON

  - name: BUILDING NFV-SOL-LIB DEPENDENCIES...DESCRIPTORS
    remote_user: ubuntu
    shell: /opt/apache-maven-3.3.9/bin/mvn clean install
    args: 
      chdir: nfv-sol-libs/NFV_MANO_SOL001_LIBS_DESCRIPTORS

  - name: BUILDING NFV-IFA-LIB DEPENDENCIES...COMMON
    remote_user: ubuntu
    shell: /opt/apache-maven-3.3.9/bin/mvn clean install  
    args:
      chdir: nfv-ifa-libs/NFV_MANO_LIBS_COMMON
  
  - name: BUILDING NFV-IFA-LIB DEPENDENCIES...DESCRIPTORS
    remote_user: ubuntu
    shell: /opt/apache-maven-3.3.9/bin/mvn clean install
    args: 
      chdir: nfv-ifa-libs/NFV_MANO_LIBS_DESCRIPTORS

  - name: BUILDING NFV-IFA-LIB DEPENDENCIES...CATALGOUES_IF
    remote_user: ubuntu
    shell: /opt/apache-maven-3.3.9/bin/mvn clean install
    args: 
      chdir: nfv-ifa-libs/NFV_MANO_LIBS_CATALOGUES_IF

  - name: COMPILING 5G APPs & SERVICEs CATALOGUE
    remote_user: ubuntu
    shell:  /opt/apache-maven-3.3.9/bin/mvn clean install
    args:
      chdir: 5gcatalogue

  - name: RUNNING 5G APPs & SERVICEs CATALOGUE
    remote_user: ubuntu
    shell:  nohup /opt/apache-maven-3.3.9/bin/mvn spring-boot:run &
    args:
      chdir: 5gcatalogue/5gcatalogue-app
