
---
# Prerequisites tasks file for 5g_catalogue

- name: Install openjdk-8
  remote_user: ubuntu
  become: true
  apt:
    update_cache: yes
    name: openjdk-8-jdk
    state: present
    
- name: Install Maven
  include_tasks : maven.yml

### Install PostgresSQL ###

# Variable configuration.
- include_tasks: pg_variables.yml

# Setup/install tasks.
- include_tasks: pg_setup.yml
  
- include_tasks: pg_initialize.yml
- include_tasks: pg_configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

