---

- name: KAFKA | Create kafka config and log paths
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    recurse: true
  with_items:
    - "{{ kafka_conf_path }}"
    - "{{ kafka_log_path }}"

- name: KAFKA | Copy server config
  become: true
  template:
    src: "{{ kafka_server_template_path }}"
    dest: "{{ kafka_conf_path }}/server.properties"
    mode: "0640"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  notify: restart kafka

- name: KAFKA | Copy log properties
  become: true
  template:
    src: "{{ kafka_log4j_template_path }}"
    dest: "{{ kafka_conf_path }}/log4j.properties"
    mode: "0644"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  notify: restart kafka

- name: KAFKA | Enable GC log
  become: true
  replace:
    path: "{{ kafka_install_path }}/bin/kafka-server-start.sh"
    regexp: ^EXTRA_ARGS=\${EXTRA_ARGS-'-name kafkaServer'}
    replace: EXTRA_ARGS=${EXTRA_ARGS-'-name kafkaServer -loggc'}
  when: kafka_gc_log_enabled

- name: KAFKA | Disable GC log
  become: true
  replace:
    path: "{{ kafka_install_path }}/bin/kafka-server-start.sh"
    regexp: ^EXTRA_ARGS=\${EXTRA_ARGS-'-name kafkaServer -loggc'}
    replace: EXTRA_ARGS=${EXTRA_ARGS-'-name kafkaServer'}
  when: not kafka_gc_log_enabled
